Feature/update1. Add PostgreSQL support, update to latest MC version
OakLoaf/LushRewards pull request #18
Opened 2024-08-13 09:07 UTC by BrainRTP

Changes:
- PostgreSQL support;
- Optimize plugin size;
- Update to latest MC version;
- Update Java and shadow version.

PostgreSQL is a very popular and convenient database. At my project everything is connected with PostgreSQL and it is very painful to see only MySQL support. That's why I added PostgreSQL support, I hope the rest of the community will like it too.

I also removed mysql & postgresql connectors from fat-jar because they can be loaded by the server kernel. Now fat-jar size is <400Kb. You can say that the size has decreased 10 times, which is very cool.

I also updated the Java & [shadow plugin to the latest versions](https://github.com/GradleUp/shadow/releases/tag/8.3.0), but this may be a moot point as it seems to affect older versions of MC as many still run with Java 17.

2024-08-13 09:09 UTC, BrainRTP commented on build.gradle.kts
> +    id("com.gradleup.shadow") version("8.3.0")
In the latest version of the plugin, the id has changed -  https://github.com/GradleUp/shadow/releases/tag/8.3.0

2024-08-13 09:15 UTC, BrainRTP commented on build.gradle.kts
> +version = "3.4.0-beta1"
ikd how you change the version, so I changed the minor version because the old config _(storage.yml)_ will no longer work on the new version because I changed it.

2024-08-13 09:15 UTC, BrainRTP commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
> +    }
PostgreSQL use snake_case to name column

2024-08-13 09:15 UTC, BrainRTP commented on src/main/java/org/lushplugins/lushrewards/data/MySqlStorage.java
> +        );
Maybe it would even be better to use String.format() here, but it seems that this option is not critical either

2024-08-13 09:15 UTC, BrainRTP commented on src/main/java/org/lushplugins/lushrewards/data/PostgreSqlStorage.java
> +        );
And here MessageFormat will definitely be better read than String.format()

2024-08-13 09:15 UTC, BrainRTP commented on src/main/resources/storage.yml
>    password: pass
Why not drop storage.yml and carry that into config.yml?

2024-08-13 13:42 UTC, OakLoaf requested changes

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
This should probably be renamed to "SqlStorage" or "AbstractSqlStorage"

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
> +    private static final Logger log = LushRewards.getInstance().getLogger();
Please remove this in favour of referencing `LushRewards.getInstance().getLogger()` individually

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
> +        String selectStatement = String.format("SELECT %s FROM %s WHERE uuid = ?;", column, table);
You can remove this variable and move the method directly into `conn#prepareStatement`

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
> +        String statement = String.format("CREATE TABLE IF NOT EXISTS %s (uuid UUID NOT NULL, PRIMARY KEY (uuid));", table);
You can remove this variable and move the method directly into `conn#prepareStatement`

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
> +            stmt.setObject(index, uuid);
You can remove this if statement in favour of overriding the method in extending classes

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
> +            stmt.setObject(index, pgObject);
You can remove this if statement in favour of overriding the method in extending classes

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/config/ConfigManager.java
> +        String storageType = storageConfig.getString("storage.type", "json");
Revert path to "type"

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/config/ConfigManager.java
> +                String schema = storageConfig.getString("storage.schema");
If we're making this change I'd like backwards compatibility for the old format, that should also put a deprecation message in logs

2024-08-13 13:42 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/PostgreSqlStorage.java
> +        );
Yeahh, I reckon I might move over to using this for formatting statements in general

2024-08-13 13:45 UTC, OakLoaf commented
Thank you for your contribution, I'm likely going to adjust the general storage setup following merging this PR. It'll be adjusted to be more similar to that of [LushMail's storage setup](https://github.com/OakLoaf/LushMail/tree/main/src/main/java/org/lushplugins/lushmail/storage).

2024-08-13 13:46 UTC, BrainRTP commented on build.gradle.kts
> +    compileOnly("org.postgresql:postgresql:${findProperty("postgresqlVersion")}")
> library loader system breaks maven central's TOS

Can you share link about this?

2024-08-13 13:50 UTC, BrainRTP commented on src/main/resources/storage.yml
> -type: json
> I'd prefer to keep this section as it was

Why do you think the past option should be kept? 

The type refers to a database. The file describes the database settings. It seems better to get rid of the storage node altogether, like this: 
```yaml
# Where user data will be stored (Options: json, mysql, postgres)
type: json
# Only for mysql and postgres  
host: localhost
# Mysql default port: 3306
# Postgres default port: 5432
port: 3306
database: dbName
schema: schemaName
user: user
password: pass
```

It seems that this option should suit you and not contradict the logic of the file (storage)

2024-08-13 13:51 UTC, BrainRTP commented on src/main/java/org/lushplugins/lushrewards/config/ConfigManager.java
> +    private static final Logger log = LushRewards.getInstance().getLogger();
> There is no need to statically store this here, please revert

I did this for the purpose of not constantly writing LushRewards.getInstance() when specifying logs. Only for the sake of reducing to three characters - log

2024-08-13 14:06 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/config/ConfigManager.java
> +    private static final Logger log = LushRewards.getInstance().getLogger();
Whilst I understand your reasoning, it's not personally the code structure I currently want to use

2024-08-13 14:06 UTC, OakLoaf commented on build.gradle.kts
> +    compileOnly("org.postgresql:postgresql:${findProperty("postgresqlVersion")}")
I can send you the [Central Repository TOS](https://central.sonatype.org/terms.html), you're obviously welcome to do further research yourself, there are a fair few conversations regarding the topic in the PaperMC Discord, just search "maven tos".

2024-08-13 16:52 UTC, OakLoaf commented on build.gradle.kts
> -        relocate("com.mysql", "org.lushplugins.lushrewards.libraries.mysql")
Don't forget to add the relocations back

2024-08-13 16:52 UTC, OakLoaf commented on build.gradle.kts
> +version = "3.4.0-beta1"
```suggestion
version = "3.3.0-beta1"
```

2024-08-13 17:10 UTC, OakLoaf commented on src/main/java/org/lushplugins/lushrewards/data/AbstractStorage.java
> +        String selectStatement = String.format("SELECT %s FROM %s WHERE uuid = ?;", column, table);
In scenarios where a statement is needed to be used in multiple places using a variable is fine. I personally would prefer indentations for now but I'll mess around with different things!

2024-08-14 14:30 UTC, OakLoaf commented
I'm happy to merge this once that last conversation has been resolved :)

2024-08-14 14:41 UTC, OakLoaf approved these changes

2024-08-14 14:42 UTC, merged

2024-08-14 14:42 UTC, OakLoaf commented
Thank you very much for your contribution!